# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonar < Formula
  desc ""
  homepage ""
  version "1.13.1"

  on_macos do
    on_intel do
      url "https://github.com/nt0xa/sonar/releases/download/v1.13.1/sonar_Darwin_x86_64.tar.gz"
      sha256 "2401a7f388c4ced18dfcc1d3d56250cf9148a8e9b2cec825828449426b4fb13f"

      def install
        bin.install "sonar"
        bash_completion.install "completions/sonar.bash" => "sonar"
        zsh_completion.install "completions/sonar.zsh" => "_sonar"
        fish_completion.install "completions/sonar.fish" => "sonar.fish"
      end
    end
    on_arm do
      url "https://github.com/nt0xa/sonar/releases/download/v1.13.1/sonar_Darwin_arm64.tar.gz"
      sha256 "6b256a0afb0baa1120be163872b52c5cc067ee15279bbdcaf82d865027cdd4f1"

      def install
        bin.install "sonar"
        bash_completion.install "completions/sonar.bash" => "sonar"
        zsh_completion.install "completions/sonar.zsh" => "_sonar"
        fish_completion.install "completions/sonar.fish" => "sonar.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nt0xa/sonar/releases/download/v1.13.1/sonar_Linux_x86_64.tar.gz"
        sha256 "acbe1e340058771670d3c82135e2d445eabb0c2aee64c03ef2443767dc52f0c1"

        def install
          bin.install "sonar"
          bash_completion.install "completions/sonar.bash" => "sonar"
          zsh_completion.install "completions/sonar.zsh" => "_sonar"
          fish_completion.install "completions/sonar.fish" => "sonar.fish"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nt0xa/sonar/releases/download/v1.13.1/sonar_Linux_arm.tar.gz"
        sha256 "89f5dcd657c25601d99e341703cde1469f7bb9539d3c0f38721c770ebb30a85d"

        def install
          bin.install "sonar"
          bash_completion.install "completions/sonar.bash" => "sonar"
          zsh_completion.install "completions/sonar.zsh" => "_sonar"
          fish_completion.install "completions/sonar.fish" => "sonar.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nt0xa/sonar/releases/download/v1.13.1/sonar_Linux_arm64.tar.gz"
        sha256 "f933f99fd0ab7c4bc83145d9ad02846eb511f56245139d14c1a4f426c60f69d4"

        def install
          bin.install "sonar"
          bash_completion.install "completions/sonar.bash" => "sonar"
          zsh_completion.install "completions/sonar.zsh" => "_sonar"
          fish_completion.install "completions/sonar.fish" => "sonar.fish"
        end
      end
    end
  end
end
