# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonar < Formula
  desc ""
  homepage ""
  version "1.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/russtone/sonar/releases/download/v1.10.0/sonar_Darwin_x86_64.tar.gz"
      sha256 "3326abe06964a28bf601776a5fbadd00ceb551de4b6d9be18c8d605fd141430f"

      def install
        bin.install "sonar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/russtone/sonar/releases/download/v1.10.0/sonar_Darwin_arm64.tar.gz"
      sha256 "40cc8ec873f3bf92c1126078e611cfca25290dcb5f77dc84239241ba027bdc75"

      def install
        bin.install "sonar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/russtone/sonar/releases/download/v1.10.0/sonar_Linux_arm.tar.gz"
      sha256 "0111106eac11ae7a59905ea2f6f7f92a28905c1ee20a8be292fd3f8c18db7ccf"

      def install
        bin.install "sonar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/russtone/sonar/releases/download/v1.10.0/sonar_Linux_x86_64.tar.gz"
      sha256 "688bf40645fe657fb83025af0965c76245ac6a04b1907b068877dd876ed599a3"

      def install
        bin.install "sonar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/russtone/sonar/releases/download/v1.10.0/sonar_Linux_arm64.tar.gz"
      sha256 "d93bc46675c6b6802a26a7dc96cc432dfaf6edad4a74cefcb04e52af37310628"

      def install
        bin.install "sonar"
      end
    end
  end
end
