# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonar < Formula
  desc ""
  homepage ""
  version "1.14.0"

  on_macos do
    on_intel do
      url "https://github.com/nt0xa/sonar/releases/download/v1.14.0/sonar_Darwin_x86_64.tar.gz"
      sha256 "f81b1fa89af5add523545a142074677487ee98e79e446ca3241d2b0ca293c955"

      def install
        bin.install "sonar"
        bash_completion.install "completions/sonar.bash" => "sonar"
        zsh_completion.install "completions/sonar.zsh" => "_sonar"
        fish_completion.install "completions/sonar.fish" => "sonar.fish"
      end
    end
    on_arm do
      url "https://github.com/nt0xa/sonar/releases/download/v1.14.0/sonar_Darwin_arm64.tar.gz"
      sha256 "4259b9e38c8b8a9758715aade7293d9acd560f1ea8548b2a8a87daa1680afbf2"

      def install
        bin.install "sonar"
        bash_completion.install "completions/sonar.bash" => "sonar"
        zsh_completion.install "completions/sonar.zsh" => "_sonar"
        fish_completion.install "completions/sonar.fish" => "sonar.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nt0xa/sonar/releases/download/v1.14.0/sonar_Linux_x86_64.tar.gz"
        sha256 "26ef4774c2fb41b0b518eca2a5f5c553ad57e6266d83ae821a9fd9a96f49d835"

        def install
          bin.install "sonar"
          bash_completion.install "completions/sonar.bash" => "sonar"
          zsh_completion.install "completions/sonar.zsh" => "_sonar"
          fish_completion.install "completions/sonar.fish" => "sonar.fish"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nt0xa/sonar/releases/download/v1.14.0/sonar_Linux_arm.tar.gz"
        sha256 "2ff7114d955812448d766408e5dadc1b527f99e1c7b69a2b81ed9f96b76c8b97"

        def install
          bin.install "sonar"
          bash_completion.install "completions/sonar.bash" => "sonar"
          zsh_completion.install "completions/sonar.zsh" => "_sonar"
          fish_completion.install "completions/sonar.fish" => "sonar.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nt0xa/sonar/releases/download/v1.14.0/sonar_Linux_arm64.tar.gz"
        sha256 "a840881add4fe8b5e5bf8abc29bb3bcafb274054471beac1bdb4a8015ec889d0"

        def install
          bin.install "sonar"
          bash_completion.install "completions/sonar.bash" => "sonar"
          zsh_completion.install "completions/sonar.zsh" => "_sonar"
          fish_completion.install "completions/sonar.fish" => "sonar.fish"
        end
      end
    end
  end
end
