# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonar" do
  version "1.25.0"

  on_macos do
    on_intel do
      sha256 "ab25a9c66d20d94fa8b2062945f6eeddfc2bb1fba5f0ab99658f55bd09bdd1f5"
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "dc85724a7f3d8d04f022b469cecfc4015ff3dd0a10215671e15acd667323b699"
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "637ecca3c781ca63a5a6121dfcad57946571b877dab6c3257c87493b29be054a"
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1a74a36c320dcd52c238ef1e3e2f3306fe67f5feeaf68e13e539946c44d3d0f5"
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Linux_arm64.tar.gz"
    end
  end

  name "sonar"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonar"
  bash_completion "completions/sonar.bash"
  fish_completion "completions/sonar.fish"
  zsh_completion "completions/sonar.zsh"

  # No zap stanza required

end
