# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonar" do
  name "sonar"
  desc ""
  homepage ""
  version "1.24.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonar"
  bash_completion "completions/sonar.bash"
  zsh_completion "completions/sonar.zsh"
  fish_completion "completions/sonar.fish"

  on_macos do
    on_intel do
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Darwin_x86_64.tar.gz"
      sha256 "679d336ba59e492ee80f452f3b46429525bf92dcc9a339dba4d6e1f5a04ac991"
    end
    on_arm do
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Darwin_arm64.tar.gz"
      sha256 "677fe4ba41de5265608c2f6b66a5b674aca560cca3cdb0065026d9a6a50f1cac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Linux_x86_64.tar.gz"
      sha256 "63c658a5b114d336d44ad6e9523b341dbbd1832cc1aec77383ae7b854ffbb8de"
    end
    on_arm do
      url "https://github.com/nt0xa/sonar/releases/download/v#{version}/sonar_Linux_arm64.tar.gz"
      sha256 "424334b4df0ad2ba2da6e1792438c95cc9ae5c8f9d94352d360e433982df9607"
    end
  end

  # No zap stanza required
end
