# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonar" do
  desc ""
  homepage ""
  version "1.23.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonar"
  bash_completion "completions/sonar.bash"
  zsh_completion "completions/sonar.zsh"
  fish_completion "completions/sonar.fish"

  on_macos do
    on_intel do
      url "https://github.com/nt0xa/sonar/releases/download/v1.23.1/sonar_Darwin_x86_64.tar.gz"
      sha256 "646d7d9cf880dba7ff4787b6aac62be252f6d4c72363816dc54c8552724dbaa1"
    end
    on_arm do
      url "https://github.com/nt0xa/sonar/releases/download/v1.23.1/sonar_Darwin_arm64.tar.gz"
      sha256 "1858896b85b9d93a95e4c4a7a77604371c8127f0d4c47313d7815e87d50a1021"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nt0xa/sonar/releases/download/v1.23.1/sonar_Linux_x86_64.tar.gz"
      sha256 "f137a368aaf99b147fa6dcc15f0155ca0a74299c36b739b7fc73bd6398e065d7"
    end
    on_arm do
      url "https://github.com/nt0xa/sonar/releases/download/v1.23.1/sonar_Linux_arm64.tar.gz"
      sha256 "70feedc396ca2803f1f68f72513c1565dc6ce1898c48e8fc43743c17b1853fc5"
    end
  end

  # No zap stanza required
end
